=head1 NAME

Parse::Marpa::Doc::To_Do - Marpa's To Do List

=head1 HIGH PRIORITY

=head2 Terminal Priorities Cannot Be Set in MDL

Priorities cannot be set in MDL for terminals.
Fix this before going beta.

Workaround:
Add extra rules with the terminals you want to prioritize on their right hand side,
and assign 
priorities to the rules.

=head2 Describe ambiguous transitions in Internals doc

Add a graf about ambiguous transitions in the Internals document.

=head2 Rewrite Marpa.pm

Move some of the stuff prior to the "Getting Started" section
elsewhere.

=head1 LOWER PRIORITY

=over 4

=item * Make code clean under perlcritic.

=item * Better evaluation of sequences -- just push onto an array via
a ref, reversing at the end if necessary.  All that code could use
better comments.

=item * C<show_tree> before first call to C<value>?  Should
it cause an error message?  How about after unsuccessful
call to C<value>?

=item * Should C<Parse::Marpa::Grammar::new> options be defaults or
overrides? -- that is they should take effect before the MDL script
or after.

=item * Allow setting Marpa options in evaluator,
and during life of recognizer?
Will require changes in internal tracking of phases.

=item * Do I need Parse::Marpa::show_value?  Won't Dumper do fine?

=item * Add a trace_choices option.  There was an option to trace
non-trivial evaluation choices in the old evaluator, and the new trace_iterations
doesn't entirely replace it.

=item * Add a show_derivation option.

=item * Allow multiple evaluators for each recognizer, or at least create a method
to safely deep copy recognizers.

=item * If recognizer did not recognize the input, don't allow evaluator to be created.

=item * Add C<{}> and C<[]> syntax to MDL production statements.

=item * Ensure C<Parse::Marpa::Internal::This::grammar> set wherever appropriate.

=item * Add option for left-to-right evaluation of rules

=item * Test proper and perl5 separation

=item * Speed-up for pre-computing lexables.  Grammar::LEXABLES, etc.

=item * Add a SYNOPSIS to the Plumbing document.

=item * Test lexing suffixes.

=item * Allow alternation?

=item * Add to test set: Basic tests of sequences.
The matrix is separation (none/perl5/proper)
and minimium count (0 or 1).
Eliminate keep vs. no-keep, right vs. left.

=item * Downgrade version conflict or semantics mismatch to warning?

=item * There are now no Parse::Marpa::Read_Only variables.  Eliminate
the namespace, and all the references to it in the documentation?

=back

=head1 MAYBE, MAYBE NOT

=head2 Lifting Restrictions on Sequence Productions

The restriction of sequences to sequence productions and of
sequence productions to a single sequence
is not the result of any limit of the Marpa parse engine.
It would not be hard to allow any number of
sequences and optional sequences on the right hand
side of any BNF production.
What's hard is figuring out how to conveniently specify their semantics.
As the right hand side of a production grows more complex,
the semantics becomes
more complex to write, more bug-prone, and harder to debug.
I'm open to revisiting this issue and lifting the restriction.

=head1 SUPPORT

See the L<support section|Parse::Marpa/SUPPORT> in the main module.

=head1 AUTHOR

Jeffrey Kegler

=head1 LICENSE AND COPYRIGHT

Copyright 2007 - 2008 Jeffrey Kegler

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl 5.10.0.

=cut

