#!/usr/bin/perl

use 5.008005;
use strict;
use Time::Elapsed 0.26;
use CPANDB::Generator;

our $VERSION = '0.01';

my $start = time;
my $cpandb = CPANDB::Generator->new;
$cpandb->run;
my $elapsed = Time::Elapsed::elapsed(time - $start);
print "Run completed in $elapsed\n";
print "Created " . $cpandb->sqlite . "\n";

exit(0);
