#!/usr/bin/perl

use 5.008005;
use strict;
use Time::Elapsed     ();
use CPANDB::Generator ();
use Xtract::Publish   ();

our $VERSION = '0.03';

my $start = time;
my $cpandb = CPANDB::Generator->new;
$cpandb->run;

# Publish the database to the current directory
Xtract::Publish->new(
	from   => $cpandb->sqlite,
	sqlite => 'cpandb.sqlite',
	trace  => 1,
	raw    => 0,
	gz     => 1,
	bz2    => 1,
	lz     => 1,
)->run;

my $elapsed = Time::Elapsed::elapsed(time - $start);
print "Run completed in $elapsed\n";

exit(0);
