#!/usr/bin/perl

use 5.008005;
use strict;
use Getopt::Long      ();
use Time::Elapsed     ();
use CPANDB::Generator ();

our $VERSION = '0.20';

# Check params
my $QUIET = 0;
my $CPANMETA = 0;
Getopt::Long::GetOptions(
	'quiet'    => \$QUIET,
	'cpanmeta' => \$CPANMETA,
) or die("Failed to parse options");

my $start  = time;
my $cpandb = CPANDB::Generator->new(
	trace    => ! $QUIET,
	cpanmeta => !! $CPANMETA,
);
$cpandb->run;

my $elapsed = Time::Elapsed::elapsed(time - $start);
print "Run completed in $elapsed\n";

exit(0);
