#!/usr/bin/perl

use 5.008;
use strict;
use warnings;
use FBP::Demo ();

our $VERSION = '0.01';

my $application = FBP::Demo->new;
unless ( $application ) {
	die "Failed to create FBP::Demo application";
}

$application->MainLoop;

exit(0);
