#!/usr/bin/perl

use 5.008;
use strict;
use warnings;
use List::Util   ();
use ADAMK::Shell ();

use vars qw{$VERSION};
BEGIN {
	$VERSION = '0.07';
}





#####################################################################
# Main Script

my $root = List::Util::first {
	defined $_ and -d $_
} (
	$ENV{ADAMK_CHECKOUT},
	'D:\cpan',
	'/home/adam/cpan',
) or die "Failed to guess repository root";

# Connect to the repository
my $shell = ADAMK::Shell->new(
	root  => 'D:\cpan',
	trace => 1,
) or die 'Failed to locate repository checkout';

# First argv is the command
my $method = shift @ARGV;
unless ( $shell->can($method) ) {
	die "Shell does not expose a $method command";
}

# Execute the command
$shell->$method(@ARGV);
