--- #YAML:1.0
name:                Parse-Marpa
version:             0.211_005
abstract:            (Alpha) Earley's algorithm with LR(0) precomputation
author:              
    - Jeffrey Kegler
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
