name: ThreatNet-Filter
version: 0.04
abstract: The ThreatNet message filtering API
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Params::Util: 0.04
  Net::IP::Match::XS: 0.03
  ThreatNet::Message: 0.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
