#!/usr/bin/perl

use 5.006;
use strict;
use warnings;

use vars qw{$VERSION};
BEGIN {
	$VERSION = '0.30';
}

# Did we get a valid file as the first param?
unless ( $ARGV[0] ) {
	print "Did not get a build configuration param\n";
	exit(0);
}

my $class = $ARGV[0];
my $dist  = $class->new;
unless ( $dist ) {
	die "Failed to create $class";
}
unless ( $dist->run ) {
	die "Failed to run";
}

exit(0);
