#!/usr/bin/perl

# Simple bootstrap loader with no functionality.

use 5.008005;
use strict;
use warnings;
use SDL::Tutorial::3DWorld ();

our $VERSION = '0.04';

# Load the game
my $game = SDL::Tutorial::3DWorld->new;
unless ( $game ) {
	print "Failed to load 3D World\n";
	exit(0);
}

# Start the game
$game->run;

exit(0);
