#!/usr/bin/perl

use 5.010;
use strict;
use warnings;
use Fatal qw(open);
use English qw( -no_match_vars ) ; 
use Data::Dumper;
use Marpa;
use Marpa::MDLex;

sub slurp {
    my $file_name = shift;
    open my $fh, q{<}, $file_name;
    return do { local $RS = undef; <$fh> };
};

my $arg_file = slurp(shift);
my $text = slurp(shift);

package My::Args;
our $marpa_options;
our $mdlex_options;
my $eval_return = eval $arg_file;

package main;
Carp::croak("eval returned false: $@") if not $eval_return;

    my $grammar = Marpa::Grammar->new(@{$marpa_options});
    $grammar->precompute();
    my $recce = Marpa::Recognizer->new( { grammar => $grammar, clone => 0 } );
    my $lexer = Marpa::MDLex->new( { recce => $recce }, @{$mdlex_options} );
    $lexer->text($text);
    my $evaler = Marpa::Evaluator->new( { recce->$recce, clone => 0 } );
    my $value = $evaler->value();


my $d = Data::Dumper->new([$value], [qw(result)]);
say $d->Dump();
