#!/usr/bin/perl

# ****************************************************************************
#
#                          Frozen-Bubble Level Editor
#
# Copyright (c) 2002 - 2003 Kim Joham and David Joham <[k|d]joham@yahoo.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#
# *****************************************************************************
#
# Design & Programming by Kim Joham and David Joham, October 2002 to January 2003
# Email - [k|d]joham at yahoo.com
# 
# pencil icon taken from the GIMP project
#
# *****************************************************************************

use strict;
use fb_stuff;
use FBLE;


# Command line options modified from frozen-bubble code
local $_ = "@ARGV";

if ( /-h/ ) { 
	print <<'END_TEXT';
Usage:  [OPTION]...
-h, --help                      display this help screen
-cb, --colourblind              use bubbles for colourblind people
-ls<filename>, 
        --levelset<filename>    directly start with the specified levelset name
-l<#n>, --level<#n>             directly start the n-th level
-fs, --fullscreen               start in fullscreen mode
END_TEXT
	exit(0);
}

our $colourblind = 0;

if ( /-cb/ or /-co/ ) {
	$colourblind = 1;
}

if ( /-ls\s*(\S+)/ or /-levelset\s*(\S+)/ ) {
	$FBLE::levelset_name = $1;
	unless ( $FBLE::levelset_name ) {
		$FBLE::levelset_name = 'default-levelset';
	}
}

if ( /-l\s*(\d+)/ or /-level\s*(\d+)/ ) {
	$FBLE::curr_level = $1;
	unless ( $FBLE::curr_level ) {
		$FBLE::curr_level = 1;
	}
}

if ( /-fs/ or /-fullscreen/ ) {
	$FBLE::command_line_fullscreen = 1;
	unless ( $FBLE::command_line_fullscreen ) {
		$FBLE::command_line_fullscreen = 0;
	}
}

my $app = SDL::App->new(
	-title  => 'frozen-bubble level editor',
	-width  => 640,
	-height => 480,
);

FBLE::init_setup('stand-alone', $app);
FBLE::handle_events();
