=head1 NAME

Marpa::Recognizer - Marpa Recognizer Objects

=head1 DESCRIPTION

Not yet written.

=head1 METHODS

=head2 value

Not yet written.

=head1 LICENSE AND COPYRIGHT

Copyright 2007-2010 Jeffrey Kegler, all rights reserved.
Marpa is free software under the Perl license.
For details see the LICENSE file in the Marpa distribution.

=cut
