=head1 NAME

Marpa::Doc::To_Do - Marpa's To Do List

=head1 MEDIUM PRIORITY

=over 4

=item * Add symbol & rule ranker tests to code_diag.t.

=item * Add a test for cycle_scale & cycle_rules.

=item * On ambiguous grammars, it may optimize to save values of reset
bocage nodes from the first reset, and simply copy them back in
on subsequent resets.  In particular for the sorted choices.
Note this optimizes only to the degree the user wants multiple
parses, or else require multiple interations to get the parse she
wants.

=item * Add optimizations when max_parses <= 1
    For example, no need to prune duplicate parses

=item * Add MAX_COUNT for rules.  Implement on one of left- and right-
    recursion only.  No immediate need for both.

=item * Add a SYNOPSIS to the Plumbing document.

=item * When rereading Internals doc, check if
parse bocage creation can probably be made cleaner.

=item * Make sure that nulling symbols can never be terminals

=back

=head1 LOW PRIORITY

=over 4

=item * Add a trace_choices option?  There was an option to trace
non-trivial evaluation choices in the old evaluator, and the trace_tasks
doesn't entirely replace it.

=item * Add a show_derivation option.

=back

=head1 MAYBE, MAYBE NOT

=over 4

=item * Allow call to 
C<show_tree> before first call to C<value>?  Should
it cause an error message?  How about after unsuccessful
call to C<value>?

=back

=head1 SUPPORT

See the L<support section|Parse::Marpa/SUPPORT> in the main module.

=head1 AUTHOR

Jeffrey Kegler

=head1 LICENSE AND COPYRIGHT

Copyright 2007 - 2009 Jeffrey Kegler

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl 5.10.0.

=cut

