name: Data-Vitals
version: 0.05
abstract: The Perl "Vital Statistics" Library
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  Test::ClassAPI: 1.02
  File::Spec: 0.82
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
