=head1 NAME

PITA::POE::SupportServer::Specification - Spec for the POE Support Server

=head1 DESCRIPTION

L<PITA>'s guest driver design for image-based drivers is based on the
following rules about how the image will be launched and run.

=head2 Surrounding Environment

The Support Server's role is to launch and provide supporting services to
emulators.

Each emulator will be executed from the command line, with the actual
command line to run determined in the main part of the driver and
provided to the support server ready to launch.

Any testing data, files, and commands will be provided inside an ISO
image provided as a CD or second hard drive, known as an "injector".
The specification for loading this image will already have been set
as part of the command line to be run.

Once the image has started, an image manager program pre-installed into
each image will take control of the image immediately at startup time.

As soon as it has been started, the image manager will contact the
support server to signal a successful startup. This will be in the
form of a HTTP C< GET / > request to a HTTP server that is part of
the support server.

After loading the test data from the injector inside the image, one of
three named tasks will be done.

=head3 ping

A "ping" instruction will cause the image manager to load, contact the
support server, and then immediately shut down.

The purpose of the ping command is only to verify that the image is a
valid PITA test image, and nothing else.

=head3 discover

In PITA, a testing context is identified by a testing "scheme" name,
and a filesystem path that defines the root of the context.

However, the specification for a the "platform" component of the
testing context is far more complex. Rather than a simple naming scheme,
it is described by a large C<HASH> containing up to 200 key/value pairs,
which  includes the normal items such as architecture but may extend
to additional values such as support for threads, or even individual
compiler optimisations.

As such, it is not realistic or practical for the user to provide any
information about the testing contexts, and so PITA supports auto-discovery
of testing contexts within an image, on the assuption that the image is
valid (previously determined using "ping").

The "discover" instruction will cause the image manager to proceed through
the "ping" sequence, and then to to some processing to determine the 
platform specification, returning it to the support server via a PUT
command.

=head3 test

The "test" instruction is performed on a discovered guest image, and
results in the provision of a software package for testing inside the
injector. The image will launch, test the package, which may or may
not result in additional requests being sent to the support server, and
then on completion the image will PUT the result of the testing to the
support server.

=head2 