---
abstract: ~
author: 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.80
  Test::File::Cleaner: 0
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.65'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Apache-HtPasswd-Shadow
no_index:
  directory:
    - inc
    - t
requires:
  Apache::Htpasswd::Shadow: 0
  File::Copy: 0
  perl: 5.005
version: 0.01
