=head1 NAME

ORDB::AU::Census2006::BcpCdB42 - ORDB::AU::Census2006 class for the bcp_cd_b42 table

=head1 DESCRIPTION

TO BE COMPLETED

=head1 METHODS

=head2 base

  # Returns 'ORDB::AU::Census2006'
  my $namespace = ORDB::AU::Census2006::BcpCdB42->base;

Normally you will only need to work directly with a table class,
and only with one ORLite package.

However, if for some reason you need to work with multiple ORLite packages
at the same time without hardcoding the root namespace all the time, you
can determine the root namespace from an object or table class with the
C<base> method.

=head2 table

  # Returns 'bcp_cd_b42'
  print ORDB::AU::Census2006::BcpCdB42->table;

While you should not need the name of table for any simple operations,
from time to time you may need it programatically. If you do need it,
you can use the C<table> method to get the table name.

=head2 load

  my $object = ORDB::AU::Census2006::BcpCdB42->load( $region_id );

If your table has single column primary key, a C<load> method will be
generated in the class. If there is no primary key, the method is not
created.

The C<load> method provides a shortcut mechanism for fetching a single
object based on the value of the primary key. However it should only
be used for cases where your code trusts the record to already exists.

It returns a C<ORDB::AU::Census2006::BcpCdB42> object, or throws an exception if the
object does not exist.

=head2 select

  # Get all objects in list context
  my @list = ORDB::AU::Census2006::BcpCdB42->select;
  
  # Get a subset of objects in scalar context
  my $array_ref = ORDB::AU::Census2006::BcpCdB42->select(
      'where region_id > ? order by region_id',
      1000,
  );

The C<select> method executes a typical SQL C<SELECT> query on the
bcp_cd_b42 table.

It takes an optional argument of a SQL phrase to be added after the
C<FROM bcp_cd_b42> section of the query, followed by variables
to be bound to the placeholders in the SQL phrase. Any SQL that is
compatible with SQLite can be used in the parameter.

Returns a list of B<ORDB::AU::Census2006::BcpCdB42> objects when called in list context, or a
reference to an C<ARRAY> of B<ORDB::AU::Census2006::BcpCdB42> objects when called in scalar
context.

Throws an exception on error, typically directly from the L<DBI> layer.

=head2 iterate

  ORDB::AU::Census2006::BcpCdB42->iterate( sub {
      print $_->region_id . "\n";
  } );

The C<iterate> method enables the processing of large tables one record at
a time without loading having to them all into memory in advance.

This plays well to the strength of SQLite, allowing it to do the work of
loading arbitrarily large stream of records from disk while retaining the
full power of Perl when processing the records.

The last argument to C<iterate> must be a subroutine reference that will be
called for each element in the list, with the object provided in the topic
variable C<$_>.

This makes the C<iterate> code fragment above functionally equivalent to the
following, except with an O(1) memory cost instead of O(n).

  foreach ( ORDB::AU::Census2006::BcpCdB42->select ) {
      print $_->region_id . "\n";
  }

You can filter the list via SQL in the same way you can with C<select>.

  ORDB::AU::Census2006::BcpCdB42->iterate(
      'order by ?', 'region_id',
      sub {
          print $_->region_id . "\n";
      }
  );

You can also use it in raw form from the root namespace for better control.
Using this form also allows for the use of arbitrarily complex queries,
including joins. Instead of being objects, rows are provided as C<ARRAY>
references when used in this form.

  ORDB::AU::Census2006->iterate(
      'select name from bcp_cd_b42 order by region_id',
      sub {
          print $_->[0] . "\n";
      }
  );

=head2 count

  # How many objects are in the table
  my $rows = ORDB::AU::Census2006::BcpCdB42->count;
  
  # How many objects 
  my $small = ORDB::AU::Census2006::BcpCdB42->count(
      'where region_id > ?',
      1000,
  );

The C<count> method executes a C<SELECT COUNT(*)> query on the
bcp_cd_b42 table.

It takes an optional argument of a SQL phrase to be added after the
C<FROM bcp_cd_b42> section of the query, followed by variables
to be bound to the placeholders in the SQL phrase. Any SQL that is
compatible with SQLite can be used in the parameter.

Returns the number of objects that match the condition.

Throws an exception on error, typically directly from the L<DBI> layer.

=head1 ACCESSORS

=head2 region_id

  if ( $object->region_id ) {
      print "Object has been inserted\n";
  } else {
      print "Object has not been inserted\n";
  }

Returns true, or throws an exception on error.

REMAINING ACCESSORS TO BE COMPLETED

=head1 SQL

The bcp_cd_b42 table was originally created with the
following SQL command.

  CREATE TABLE bcp_cd_b42 (
      region_id INTEGER NOT NULL PRIMARY KEY,
      b6023 REAL NOT NULL,
      b6024 REAL NOT NULL,
      b6025 REAL NOT NULL,
      b6026 REAL NOT NULL,
      b6027 REAL NOT NULL,
      b6028 REAL NOT NULL,
      b6029 REAL NOT NULL,
      b6030 REAL NOT NULL,
      b6031 REAL NOT NULL,
      b6032 REAL NOT NULL,
      b6033 REAL NOT NULL,
      b6034 REAL NOT NULL,
      b6035 REAL NOT NULL,
      b6036 REAL NOT NULL,
      b6037 REAL NOT NULL,
      b6038 REAL NOT NULL,
      b6039 REAL NOT NULL,
      b6040 REAL NOT NULL,
      b6041 REAL NOT NULL,
      b6042 REAL NOT NULL,
      b6043 REAL NOT NULL,
      b6044 REAL NOT NULL,
      b6045 REAL NOT NULL,
      b6046 REAL NOT NULL,
      b6047 REAL NOT NULL,
      b6048 REAL NOT NULL,
      b6049 REAL NOT NULL,
      b6050 REAL NOT NULL,
      b6051 REAL NOT NULL,
      b6052 REAL NOT NULL,
      b6053 REAL NOT NULL,
      b6054 REAL NOT NULL,
      b6055 REAL NOT NULL,
      b6056 REAL NOT NULL,
      b6057 REAL NOT NULL,
      b6058 REAL NOT NULL,
      b6059 REAL NOT NULL,
      b6060 REAL NOT NULL,
      b6061 REAL NOT NULL,
      b6062 REAL NOT NULL,
      b6063 REAL NOT NULL,
      b6064 REAL NOT NULL,
      b6065 REAL NOT NULL,
      b6066 REAL NOT NULL,
      b6067 REAL NOT NULL,
      b6068 REAL NOT NULL,
      b6069 REAL NOT NULL,
      b6070 REAL NOT NULL,
      b6071 REAL NOT NULL,
      b6072 REAL NOT NULL,
      b6073 REAL NOT NULL,
      b6074 REAL NOT NULL,
      b6075 REAL NOT NULL,
      b6076 REAL NOT NULL,
      b6077 REAL NOT NULL,
      b6078 REAL NOT NULL,
      b6079 REAL NOT NULL,
      b6080 REAL NOT NULL,
      b6081 REAL NOT NULL,
      b6082 REAL NOT NULL,
      b6083 REAL NOT NULL,
      b6084 REAL NOT NULL,
      b6085 REAL NOT NULL,
      b6086 REAL NOT NULL,
      b6087 REAL NOT NULL,
      b6088 REAL NOT NULL,
      b6089 REAL NOT NULL,
      b6090 REAL NOT NULL,
      b6091 REAL NOT NULL,
      b6092 REAL NOT NULL,
      b6093 REAL NOT NULL,
      b6094 REAL NOT NULL,
      b6095 REAL NOT NULL,
      b6096 REAL NOT NULL,
      b6097 REAL NOT NULL,
      b6098 REAL NOT NULL,
      b6099 REAL NOT NULL,
      b6100 REAL NOT NULL,
      b6101 REAL NOT NULL,
      b6102 REAL NOT NULL,
      b6103 REAL NOT NULL,
      b6104 REAL NOT NULL,
      b6105 REAL NOT NULL,
      b6106 REAL NOT NULL,
      b6107 REAL NOT NULL,
      b6108 REAL NOT NULL,
      b6109 REAL NOT NULL,
      b6110 REAL NOT NULL,
      b6111 REAL NOT NULL,
      b6112 REAL NOT NULL,
      b6113 REAL NOT NULL,
      b6114 REAL NOT NULL,
      b6115 REAL NOT NULL,
      b6116 REAL NOT NULL,
      b6117 REAL NOT NULL,
      b6118 REAL NOT NULL,
      b6119 REAL NOT NULL,
      b6120 REAL NOT NULL,
      b6121 REAL NOT NULL,
      b6122 REAL NOT NULL,
      b6123 REAL NOT NULL,
      b6124 REAL NOT NULL,
      b6125 REAL NOT NULL,
      b6126 REAL NOT NULL,
      b6127 REAL NOT NULL,
      b6128 REAL NOT NULL,
      b6129 REAL NOT NULL,
      b6130 REAL NOT NULL,
      b6131 REAL NOT NULL,
      b6132 REAL NOT NULL,
      b6133 REAL NOT NULL,
      b6134 REAL NOT NULL,
      b6135 REAL NOT NULL,
      b6136 REAL NOT NULL,
      b6137 REAL NOT NULL,
      b6138 REAL NOT NULL,
      b6139 REAL NOT NULL,
      b6140 REAL NOT NULL,
      b6141 REAL NOT NULL,
      b6142 REAL NOT NULL,
      b6143 REAL NOT NULL,
      b6144 REAL NOT NULL,
      b6145 REAL NOT NULL,
      b6146 REAL NOT NULL,
      b6147 REAL NOT NULL,
      b6148 REAL NOT NULL,
      b6149 REAL NOT NULL,
      b6150 REAL NOT NULL,
      b6151 REAL NOT NULL,
      b6152 REAL NOT NULL,
      b6153 REAL NOT NULL,
      b6154 REAL NOT NULL,
      b6155 REAL NOT NULL,
      b6156 REAL NOT NULL,
      b6157 REAL NOT NULL,
      b6158 REAL NOT NULL,
      b6159 REAL NOT NULL,
      b6160 REAL NOT NULL,
      b6161 REAL NOT NULL,
      b6162 REAL NOT NULL,
      b6163 REAL NOT NULL,
      b6164 REAL NOT NULL,
      b6165 REAL NOT NULL,
      b6166 REAL NOT NULL,
      b6167 REAL NOT NULL,
      b6168 REAL NOT NULL,
      b6169 REAL NOT NULL,
      b6170 REAL NOT NULL,
      b6171 REAL NOT NULL,
      b6172 REAL NOT NULL,
      b6173 REAL NOT NULL,
      b6174 REAL NOT NULL,
      b6175 REAL NOT NULL,
      b6176 REAL NOT NULL,
      b6177 REAL NOT NULL,
      b6178 REAL NOT NULL,
      b6179 REAL NOT NULL,
      b6180 REAL NOT NULL,
      b6181 REAL NOT NULL,
      b6182 REAL NOT NULL,
      b6183 REAL NOT NULL,
      b6184 REAL NOT NULL,
      b6185 REAL NOT NULL,
      b6186 REAL NOT NULL,
      b6187 REAL NOT NULL,
      b6188 REAL NOT NULL,
      b6189 REAL NOT NULL,
      b6190 REAL NOT NULL,
      b6191 REAL NOT NULL,
      b6192 REAL NOT NULL,
      b6193 REAL NOT NULL,
      b6194 REAL NOT NULL,
      b6195 REAL NOT NULL,
      b6196 REAL NOT NULL,
      b6197 REAL NOT NULL,
      b6198 REAL NOT NULL,
      b6199 REAL NOT NULL,
      b6200 REAL NOT NULL,
      b6201 REAL NOT NULL,
      b6202 REAL NOT NULL,
      b6203 REAL NOT NULL,
      b6204 REAL NOT NULL,
      b6205 REAL NOT NULL,
      b6206 REAL NOT NULL,
      b6207 REAL NOT NULL,
      b6208 REAL NOT NULL,
      b6209 REAL NOT NULL,
      b6210 REAL NOT NULL,
      b6211 REAL NOT NULL,
      b6212 REAL NOT NULL,
      b6213 REAL NOT NULL,
      b6214 REAL NOT NULL,
      b6215 REAL NOT NULL,
      b6216 REAL NOT NULL,
      b6217 REAL NOT NULL,
      b6218 REAL NOT NULL,
      b6219 REAL NOT NULL,
      b6220 REAL NOT NULL,
      b6221 REAL NOT NULL,
      b6222 REAL NOT NULL,
      b6223 REAL NOT NULL,
      b6224 REAL NOT NULL,
      b6225 REAL NOT NULL,
      b6226 REAL NOT NULL,
      b6227 REAL NOT NULL,
      b6228 REAL NOT NULL,
      b6229 REAL NOT NULL,
      b6230 REAL NOT NULL,
      b6231 REAL NOT NULL,
      b6232 REAL NOT NULL,
      b6233 REAL NOT NULL,
      b6234 REAL NOT NULL,
      b6235 REAL NOT NULL,
      b6236 REAL NOT NULL,
      b6237 REAL NOT NULL,
      b6238 REAL NOT NULL,
      b6239 REAL NOT NULL,
      b6240 REAL NOT NULL,
      b6241 REAL NOT NULL,
      b6242 REAL NOT NULL,
      b6243 REAL NOT NULL,
      b6244 REAL NOT NULL,
      b6245 REAL NOT NULL,
      b6246 REAL NOT NULL,
      b6247 REAL NOT NULL,
      b6248 REAL NOT NULL,
      b6249 REAL NOT NULL,
      b6250 REAL NOT NULL,
      b6251 REAL NOT NULL,
      b6252 REAL NOT NULL,
      b6253 REAL NOT NULL,
      b6254 REAL NOT NULL,
      b6255 REAL NOT NULL,
      b6256 REAL NOT NULL,
      b6257 REAL NOT NULL,
      b6258 REAL NOT NULL,
      b6259 REAL NOT NULL,
      b6260 REAL NOT NULL,
      b6261 REAL NOT NULL,
      b6262 REAL NOT NULL,
      b6263 REAL NOT NULL,
      b6264 REAL NOT NULL,
      b6265 REAL NOT NULL,
      b6266 REAL NOT NULL,
      b6267 REAL NOT NULL,
      b6268 REAL NOT NULL,
      b6269 REAL NOT NULL,
      b6270 REAL NOT NULL,
      b6271 REAL NOT NULL,
      b6272 REAL NOT NULL,
      b6273 REAL NOT NULL,
      b6274 REAL NOT NULL,
      b6275 REAL NOT NULL,
      b6276 REAL NOT NULL,
      b6277 REAL NOT NULL,
      b6278 REAL NOT NULL,
      b6279 REAL NOT NULL,
      b6280 REAL NOT NULL,
      b6281 REAL NOT NULL,
      b6282 REAL NOT NULL,
      b6283 REAL NOT NULL,
      b6284 REAL NOT NULL,
      b6285 REAL NOT NULL,
      b6286 REAL NOT NULL,
      b6287 REAL NOT NULL,
      b6288 REAL NOT NULL,
      b6289 REAL NOT NULL,
      b6290 REAL NOT NULL,
      b6291 REAL NOT NULL,
      b6292 REAL NOT NULL,
      b6293 REAL NOT NULL,
      b6294 REAL NOT NULL,
      b6295 REAL NOT NULL,
      b6296 REAL NOT NULL,
      b6297 REAL NOT NULL,
      b6298 REAL NOT NULL,
      b6299 REAL NOT NULL,
      b6300 REAL NOT NULL,
      b6301 REAL NOT NULL,
      b6302 REAL NOT NULL,
      b6303 REAL NOT NULL,
      b6304 REAL NOT NULL,
      b6305 REAL NOT NULL,
      b6306 REAL NOT NULL,
      b6307 REAL NOT NULL,
      b6308 REAL NOT NULL,
      b6309 REAL NOT NULL,
      b6310 REAL NOT NULL,
      b6311 REAL NOT NULL,
      b6312 REAL NOT NULL,
      b6313 REAL NOT NULL,
      b6314 REAL NOT NULL,
      b6315 REAL NOT NULL,
      b6316 REAL NOT NULL,
      b6317 REAL NOT NULL,
      b6318 REAL NOT NULL,
      b6319 REAL NOT NULL,
      b6320 REAL NOT NULL,
      b6321 REAL NOT NULL,
      b6322 REAL NOT NULL,
      b6323 REAL NOT NULL,
      b6324 REAL NOT NULL,
      b6325 REAL NOT NULL,
      b6326 REAL NOT NULL,
      b6327 REAL NOT NULL,
      b6328 REAL NOT NULL,
      b6329 REAL NOT NULL,
      b6330 REAL NOT NULL,
      b6331 REAL NOT NULL,
      b6332 REAL NOT NULL,
      b6333 REAL NOT NULL,
      b6334 REAL NOT NULL,
      b6335 REAL NOT NULL,
      b6336 REAL NOT NULL,
      b6337 REAL NOT NULL,
      b6338 REAL NOT NULL,
      b6339 REAL NOT NULL,
      b6340 REAL NOT NULL,
      b6341 REAL NOT NULL,
      b6342 REAL NOT NULL,
      b6343 REAL NOT NULL,
      b6344 REAL NOT NULL,
      b6345 REAL NOT NULL,
      b6346 REAL NOT NULL,
      b6347 REAL NOT NULL,
      b6348 REAL NOT NULL,
      b6349 REAL NOT NULL,
      b6350 REAL NOT NULL,
      b6351 REAL NOT NULL,
      b6352 REAL NOT NULL,
      b6353 REAL NOT NULL,
      b6354 REAL NOT NULL,
      b6355 REAL NOT NULL,
      b6356 REAL NOT NULL,
      b6357 REAL NOT NULL,
      b6358 REAL NOT NULL,
      b6359 REAL NOT NULL,
      b6360 REAL NOT NULL,
      b6361 REAL NOT NULL,
      b6362 REAL NOT NULL,
      b6363 REAL NOT NULL,
      b6364 REAL NOT NULL,
      b6365 REAL NOT NULL,
      b6366 REAL NOT NULL,
      b6367 REAL NOT NULL,
      b6368 REAL NOT NULL,
      b6369 REAL NOT NULL,
      b6370 REAL NOT NULL,
      b6371 REAL NOT NULL,
      b6372 REAL NOT NULL,
      b6373 REAL NOT NULL,
      b6374 REAL NOT NULL,
      b6375 REAL NOT NULL,
      b6376 REAL NOT NULL,
      b6377 REAL NOT NULL,
      b6378 REAL NOT NULL,
      b6379 REAL NOT NULL,
      b6380 REAL NOT NULL,
      b6381 REAL NOT NULL,
      b6382 REAL NOT NULL,
      b6383 REAL NOT NULL,
      b6384 REAL NOT NULL,
      b6385 REAL NOT NULL,
      b6386 REAL NOT NULL,
      b6387 REAL NOT NULL,
      b6388 REAL NOT NULL,
      b6389 REAL NOT NULL,
      b6390 REAL NOT NULL,
      b6391 REAL NOT NULL,
      b6392 REAL NOT NULL,
      b6393 REAL NOT NULL,
      b6394 REAL NOT NULL,
      b6395 REAL NOT NULL,
      b6396 REAL NOT NULL,
      b6397 REAL NOT NULL,
      b6398 REAL NOT NULL,
      b6399 REAL NOT NULL,
      b6400 REAL NOT NULL,
      b6401 REAL NOT NULL,
      b6402 REAL NOT NULL,
      b6403 REAL NOT NULL,
      b6404 REAL NOT NULL,
      b6405 REAL NOT NULL,
      b6406 REAL NOT NULL,
      b6407 REAL NOT NULL,
      b6408 REAL NOT NULL,
      b6409 REAL NOT NULL,
      b6410 REAL NOT NULL,
      b6411 REAL NOT NULL,
      b6412 REAL NOT NULL,
      b6413 REAL NOT NULL,
      b6414 REAL NOT NULL,
      b6415 REAL NOT NULL,
      b6416 REAL NOT NULL,
      b6417 REAL NOT NULL,
      b6418 REAL NOT NULL,
      b6419 REAL NOT NULL,
      b6420 REAL NOT NULL,
      b6421 REAL NOT NULL,
      b6422 REAL NOT NULL,
      b6423 REAL NOT NULL,
      b6424 REAL NOT NULL,
      b6425 REAL NOT NULL,
      b6426 REAL NOT NULL,
      b6427 REAL NOT NULL,
      b6428 REAL NOT NULL,
      b6429 REAL NOT NULL,
      b6430 REAL NOT NULL,
      b6431 REAL NOT NULL,
      b6432 REAL NOT NULL,
      b6433 REAL NOT NULL,
      b6434 REAL NOT NULL,
      b6435 REAL NOT NULL,
      b6436 REAL NOT NULL,
      b6437 REAL NOT NULL,
      b6438 REAL NOT NULL,
      b6439 REAL NOT NULL,
      b6440 REAL NOT NULL,
      b6441 REAL NOT NULL,
      b6442 REAL NOT NULL,
      b6443 REAL NOT NULL,
      b6444 REAL NOT NULL,
      b6445 REAL NOT NULL,
      b6446 REAL NOT NULL,
      b6447 REAL NOT NULL,
      b6448 REAL NOT NULL,
      b6449 REAL NOT NULL,
      b6450 REAL NOT NULL,
      b6451 REAL NOT NULL,
      b6452 REAL NOT NULL,
      b6453 REAL NOT NULL,
      b6454 REAL NOT NULL,
      b6455 REAL NOT NULL,
      b6456 REAL NOT NULL,
      b6457 REAL NOT NULL,
      b6458 REAL NOT NULL,
      b6459 REAL NOT NULL,
      b6460 REAL NOT NULL,
      b6461 REAL NOT NULL,
      b6462 REAL NOT NULL,
      b6463 REAL NOT NULL,
      b6464 REAL NOT NULL,
      b6465 REAL NOT NULL,
      b6466 REAL NOT NULL,
      b6467 REAL NOT NULL,
      b6468 REAL NOT NULL,
      b6469 REAL NOT NULL,
      b6470 REAL NOT NULL,
      b6471 REAL NOT NULL,
      b6472 REAL NOT NULL,
      b6473 REAL NOT NULL,
      b6474 REAL NOT NULL,
      b6475 REAL NOT NULL,
      b6476 REAL NOT NULL,
      b6477 REAL NOT NULL,
      b6478 REAL NOT NULL,
      b6479 REAL NOT NULL,
      b6480 REAL NOT NULL,
      b6481 REAL NOT NULL,
      b6482 REAL NOT NULL,
      b6483 REAL NOT NULL,
      b6484 REAL NOT NULL,
      b6485 REAL NOT NULL,
      b6486 REAL NOT NULL,
      b6487 REAL NOT NULL,
      b6488 REAL NOT NULL,
      b6489 REAL NOT NULL,
      b6490 REAL NOT NULL,
      b6491 REAL NOT NULL,
      b6492 REAL NOT NULL,
      b6493 REAL NOT NULL,
      b6494 REAL NOT NULL,
      b6495 REAL NOT NULL,
      b6496 REAL NOT NULL,
      b6497 REAL NOT NULL,
      b6498 REAL NOT NULL,
      b6499 REAL NOT NULL,
      b6500 REAL NOT NULL,
      b6501 REAL NOT NULL,
      b6502 REAL NOT NULL,
      b6503 REAL NOT NULL,
      b6504 REAL NOT NULL,
      b6505 REAL NOT NULL,
      b6506 REAL NOT NULL,
      b6507 REAL NOT NULL,
      b6508 REAL NOT NULL,
      b6509 REAL NOT NULL,
      b6510 REAL NOT NULL,
      b6511 REAL NOT NULL,
      b6512 REAL NOT NULL,
      b6513 REAL NOT NULL,
      b6514 REAL NOT NULL,
      b6515 REAL NOT NULL,
      b6516 REAL NOT NULL,
      b6517 REAL NOT NULL,
      b6518 REAL NOT NULL,
      b6519 REAL NOT NULL,
      b6520 REAL NOT NULL,
      b6521 REAL NOT NULL,
      b6522 REAL NOT NULL,
      b6523 REAL NOT NULL,
      b6524 REAL NOT NULL,
      b6525 REAL NOT NULL,
      b6526 REAL NOT NULL,
      b6527 REAL NOT NULL,
      b6528 REAL NOT NULL,
      b6529 REAL NOT NULL,
      b6530 REAL NOT NULL,
      b6531 REAL NOT NULL,
      b6532 REAL NOT NULL,
      b6533 REAL NOT NULL,
      b6534 REAL NOT NULL,
      b6535 REAL NOT NULL,
      b6536 REAL NOT NULL,
      b6537 REAL NOT NULL,
      b6538 REAL NOT NULL,
      b6539 REAL NOT NULL,
      b6540 REAL NOT NULL,
      b6541 REAL NOT NULL,
      b6542 REAL NOT NULL,
      b6543 REAL NOT NULL,
      b6544 REAL NOT NULL,
      b6545 REAL NOT NULL,
      b6546 REAL NOT NULL,
      b6547 REAL NOT NULL,
      b6548 REAL NOT NULL,
      b6549 REAL NOT NULL,
      b6550 REAL NOT NULL,
      b6551 REAL NOT NULL,
      b6552 REAL NOT NULL,
      b6553 REAL NOT NULL,
      b6554 REAL NOT NULL,
      b6555 REAL NOT NULL,
      b6556 REAL NOT NULL,
      b6557 REAL NOT NULL,
      b6558 REAL NOT NULL,
      b6559 REAL NOT NULL,
      b6560 REAL NOT NULL,
      b6561 REAL NOT NULL,
      b6562 REAL NOT NULL,
      b6563 REAL NOT NULL,
      b6564 REAL NOT NULL,
      b6565 REAL NOT NULL,
      b6566 REAL NOT NULL,
      b6567 REAL NOT NULL,
      b6568 REAL NOT NULL,
      b6569 REAL NOT NULL,
      b6570 REAL NOT NULL,
      b6571 REAL NOT NULL,
      b6572 REAL NOT NULL,
      b6573 REAL NOT NULL,
      b6574 REAL NOT NULL,
      b6575 REAL NOT NULL,
      b6576 REAL NOT NULL,
      b6577 REAL NOT NULL,
      b6578 REAL NOT NULL,
      b6579 REAL NOT NULL,
      b6580 REAL NOT NULL,
      b6581 REAL NOT NULL,
      b6582 REAL NOT NULL,
      b6583 REAL NOT NULL,
      b6584 REAL NOT NULL,
      b6585 REAL NOT NULL,
      b6586 REAL NOT NULL,
      b6587 REAL NOT NULL,
      b6588 REAL NOT NULL,
      b6589 REAL NOT NULL,
      b6590 REAL NOT NULL,
      b6591 REAL NOT NULL,
      b6592 REAL NOT NULL,
      b6593 REAL NOT NULL,
      b6594 REAL NOT NULL,
      b6595 REAL NOT NULL,
      b6596 REAL NOT NULL,
      b6597 REAL NOT NULL,
      b6598 REAL NOT NULL,
      b6599 REAL NOT NULL,
      b6600 REAL NOT NULL,
      b6601 REAL NOT NULL,
      b6602 REAL NOT NULL,
      b6603 REAL NOT NULL,
      b6604 REAL NOT NULL,
      b6605 REAL NOT NULL,
      b6606 REAL NOT NULL,
      b6607 REAL NOT NULL,
      b6608 REAL NOT NULL,
      b6609 REAL NOT NULL,
      b6610 REAL NOT NULL,
      b6611 REAL NOT NULL,
      b6612 REAL NOT NULL,
      b6613 REAL NOT NULL,
      b6614 REAL NOT NULL,
      b6615 REAL NOT NULL,
      b6616 REAL NOT NULL,
      b6617 REAL NOT NULL,
      b6618 REAL NOT NULL,
      b6619 REAL NOT NULL,
      b6620 REAL NOT NULL,
      b6621 REAL NOT NULL,
      b6622 REAL NOT NULL,
      b6623 REAL NOT NULL,
      b6624 REAL NOT NULL,
      b6625 REAL NOT NULL,
      b6626 REAL NOT NULL,
      b6627 REAL NOT NULL,
      b6628 REAL NOT NULL,
      b6629 REAL NOT NULL,
      b6630 REAL NOT NULL,
      b6631 REAL NOT NULL,
      b6632 REAL NOT NULL,
      b6633 REAL NOT NULL,
      b6634 REAL NOT NULL,
      b6635 REAL NOT NULL,
      b6636 REAL NOT NULL,
      b6637 REAL NOT NULL,
      b6638 REAL NOT NULL,
      b6639 REAL NOT NULL,
      b6640 REAL NOT NULL,
      b6641 REAL NOT NULL,
      b6642 REAL NOT NULL,
      b6643 REAL NOT NULL,
      b6644 REAL NOT NULL,
      b6645 REAL NOT NULL,
      b6646 REAL NOT NULL,
      b6647 REAL NOT NULL,
      b6648 REAL NOT NULL,
      b6649 REAL NOT NULL,
      b6650 REAL NOT NULL,
      b6651 REAL NOT NULL,
      b6652 REAL NOT NULL
  )

=head1 SUPPORT

ORDB::AU::Census2006::BcpCdB42 is part of the L<ORDB::AU::Census2006> API.

See the documentation for L<ORDB::AU::Census2006> for more information.

=head1 AUTHOR

AdamKennedy E<lt>adamk@cpan.orgE<gt>

=head1 COPYRIGHT

Copyright 2009 - 2012 AdamKennedy.

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

The full text of the license can be found in the
LICENSE file included with this module.

