#!/usr/bin/perl

# Setup/installer program

use strict;
use File::Spec;
use File::Copy;
use File::Which;
use Getopt::Long;
use Term::Prompt;
use LWP::Simple;

# Define the configuration
my $PATH = undef;
my $URI  = undef;

# Get any params from the command line
GetOptions(
	'path=s' => \$PATH,
	'uri=s'  => \$URI,
);

# Check the path information
unless ( defined $PATH ) {
	$PATH = prompt( "x", "CGI Directory:", '', File::Spec->curdir );
}
unless ( -d $PATH ) {
	die "The directory '$PATH' does not exist";
}
unless ( -w $PATH ) {
	die "No write permissions to '$PATH'";
}
unless ( defined $CGI ) {
	$URI = prompt( "x", "CGI URL:", '', '' );
}

sub copy_files {
	
}

sub find_module {
	my @parts = split /::/, $_[0];
	my @found =
		grep { -f $_ }
		map  { catdir( $_, @parts ) . '.pm' }
		grep { -d $_ } @INC;
	return $found[0];
}
