#!/usr/bin/perl

use 5.005;
use strict;
use PPI::App::ppi_version ();

use vars qw{$VERSION};
BEGIN {
	$|       = 1;
	$^W      = 1;
        $VERSION = '0.11';
}

exit(
	PPI::App::ppi_version::main(@ARGV)
);
