#!/usr/bin/perl

use 5.006;
use strict;
use warnings;
use PPI::App::ppi_copyright ();

use vars qw{$VERSION};
BEGIN {
        $VERSION = '0.13';
}

$| = 1;
PPI::App::ppi_copyright::main(@ARGV);
exit(0);
